end:
- 90
- 20
height: 100
map_name: TrainTrackEmpty
obs_size:
- 5
- 8
obstacles:
  0:
  - 40
  - 75
  1:
  - 25
  - 45
  2:
  - 70
  - 60
  3:
  - 50
  - 30
  4:
  - 75
  - 15
  5:
  - 10
  - 80
  6:
  - 20
  - 10
  7:
  - 60
  - 30
  8:
  - 75
  - 35
  9:
  - 20
  - 70
  10:
  - 50
  - 50
start:
- 53
- 5
width: 100