end:
- 50
- 90
height: 100
map_name: TrainTrackEmpty
obs_size:
- 8
- 14
obstacles:
  0:
  - 46
  - 50
  # 1:
  # - 25
  # - 45
  # 2:
  # - 70
  # - 60
  # 3:
  # - 50
  # - 30
  # 4:
  # - 75
  # - 15
  # 5:
  # - 10
  # - 80
  # 6:
  # - 20
  # - 10
start:
- 50
- 15
width: 100
