end:
- 90
- 20
height: 100
map_name: TrainTrackEmpty
obs_size:
- 5
- 8
obstacles:
  0:
  - 40
  - 75
  1:
  - 25
  - 45
  2:
  - 70
  - 60
  3:
  - 45
  - 30
  4:
  - 80
  - 15
  5:
  - 10
  - 80
  6:
  - 20
  - 10
  7:
  - 30
  - 20
  8:
  - 75
  - 35
  9:
  - 20
  - 70
  10:
  - 55
  - 55
  11:
  - 78
  - 80
  12:
  - 58
  - 10
start:
- 53
- 5
width: 100